<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DependenciesDirectory>$(MSBuildProjectDirectory)/../Dependencies</DependenciesDirectory>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <Reference Include="Allumeria">
      <HintPath>$(DependenciesDirectory)/Allumeria.dll</HintPath>
    </Reference>
    <Reference Include="OpenTK.Mathematics">
      <HintPath>$(DependenciesDirectory)/OpenTK.Mathematics.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
