<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="AlluLoader.API">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Allumeria Demo\AlluLoader\Libraries\AlluLoader.API.dll</HintPath>
    </Reference>
    <Reference Include="Allumeria">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Allumeria Demo\publicized_assemblies\Allumeria_publicized.dll</HintPath>
    </Reference>
    <Reference Include="OpenTK.Mathematics">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Allumeria Demo\OpenTK.Mathematics.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
